version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
permissions:
  - object: /var/www/html
    owner: www-data
    group: www-data
hooks:
  ApplicationStop:
    - location: scripts/stop-server.sh
      timeout: 30
  BeforeInstall:
    - location: scripts/install-dependencies.sh
      timeout: 300
  AfterInstall:
    - location: scripts/start-server.sh
      timeout: 30
